vich_uploader:
    db_driver: orm

    mappings:
        exercice_solution:
             uri_prefix: /images/exercices
             upload_destination: '%kernel.project_dir%/public/images/exercices'
             namer: Vich\UploaderBundle\Naming\UniqidNamer