<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBxiwaio\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBxiwaio/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBxiwaio.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBxiwaio\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBxiwaio\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bxiwaio',
    'container.build_id' => '076c02c7',
    'container.build_time' => 1588209671,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBxiwaio');
