<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI77gxzk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI77gxzk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI77gxzk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI77gxzk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI77gxzk\App_KernelDevDebugContainer([
    'container.build_hash' => 'I77gxzk',
    'container.build_id' => '18701c7c',
    'container.build_time' => 1588164079,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI77gxzk');
