<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVDnS9kO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVDnS9kO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVDnS9kO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVDnS9kO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVDnS9kO\App_KernelDevDebugContainer([
    'container.build_hash' => 'VDnS9kO',
    'container.build_id' => '7271c5b1',
    'container.build_time' => 1588169054,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVDnS9kO');
